import { POST_ACTIONS_PREFIX } from './actionsPrefix'

export const GET_LIST_REQUEST = `${POST_ACTIONS_PREFIX}FETCH_POSTS_REQUEST`
export const GET_LIST_SUCCESS = `${POST_ACTIONS_PREFIX}FETCH_POSTS_SUCCESS`
export const GET_LIST_FAILURE = `${POST_ACTIONS_PREFIX}FETCH_POSTS_FAILURE`
