import { AUTHOR_ACTIONS_PREFIX } from '@entities/Author'

export const GET_DETAIL_REQUEST = `${AUTHOR_ACTIONS_PREFIX}GET_DETAIL_REQUEST`
export const GET_DETAIL_SUCCESS = `${AUTHOR_ACTIONS_PREFIX}GET_DETAIL_SUCCESS`
export const GET_DETAIL_FAILURE = `${AUTHOR_ACTIONS_PREFIX}GET_DETAIL_FAILURE`

export const UPDATE_REQUEST = `${AUTHOR_ACTIONS_PREFIX}UPDATE_REQUEST`
export const UPDATE_SUCCESS = `${AUTHOR_ACTIONS_PREFIX}UPDATE_SUCCESS`
export const UPDATE_FAILURE = `${AUTHOR_ACTIONS_PREFIX}UPDATE_FAILURE`
