import { POST_ACTIONS_PREFIX } from '@entities/Post'

export const CREATE_REQUEST = `${POST_ACTIONS_PREFIX}CREATE_REQUEST`
export const CREATE_SUCCESS = `${POST_ACTIONS_PREFIX}CREATE_SUCCESS`
export const CREATE_FAILURE = `${POST_ACTIONS_PREFIX}CREATE_FAILURE`
