import { POST_ACTIONS_PREFIX } from '@entities/Post'

// Получение поста
export const GET_DETAIL_REQUEST = `${POST_ACTIONS_PREFIX}GET_DETAIL_REQUEST`
export const GET_DETAIL_SUCCESS = `${POST_ACTIONS_PREFIX}GET_DETAIL_SUCCESS`
export const GET_DETAIL_FAILURE = `${POST_ACTIONS_PREFIX}GET_DETAIL_FAILURE`

// Редактирование поста
export const UPDATE_REQUEST = `${POST_ACTIONS_PREFIX}UPDATE_REQUEST`
export const UPDATE_SUCCESS = `${POST_ACTIONS_PREFIX}UPDATE_SUCCESS`
export const UPDATE_FAILURE = `${POST_ACTIONS_PREFIX}UPDATE_FAILURE`
