import { AUTHOR_ACTIONS_PREFIX } from '@entities/Author'

export const SET_DELETE_MODAL_OPEN = `${AUTHOR_ACTIONS_PREFIX}SET_DELETE_AUTHOR_MODAL_OPEN`
export const DELETE_REQUEST = `${AUTHOR_ACTIONS_PREFIX}DELETE_AUTHOR_REQUEST`
export const DELETE_SUCCESS = `${AUTHOR_ACTIONS_PREFIX}DELETE_AUTHOR_SUCCESS`
export const DELETE_FAILURE = `${AUTHOR_ACTIONS_PREFIX}DELETE_AUTHOR_FAILURE`
