import { AUTHOR_ACTIONS_PREFIX } from './actionsPrefix'

export const GET_LIST_REQUEST = `${AUTHOR_ACTIONS_PREFIX}GET_LIST_REQUEST`
export const GET_LIST_SUCCESS = `${AUTHOR_ACTIONS_PREFIX}GET_LIST_SUCCESS`
export const GET_LIST_FAILURE = `${AUTHOR_ACTIONS_PREFIX}GET_LIST_FAILURE`
