import { AUTHOR_ACTIONS_PREFIX } from '@entities/Author'

export const CREATE_REQUEST = `${AUTHOR_ACTIONS_PREFIX}/CREATE_AUTHOR_REQUEST`
export const CREATE_SUCCESS = `${AUTHOR_ACTIONS_PREFIX}/CREATE_AUTHOR_SUCCESS`
export const CREATE_FAILURE = `${AUTHOR_ACTIONS_PREFIX}/CREATE_AUTHOR_FAILURE`
