import { POST_ACTIONS_PREFIX } from '@entities/Post'

export const DELETE_REQUEST = `${POST_ACTIONS_PREFIX}DELETE_POST_REQUEST`
export const DELETE_SUCCESS = `${POST_ACTIONS_PREFIX}DELETE_POST_SUCCESS`
export const DELETE_FAILURE = `${POST_ACTIONS_PREFIX}DELETE_POST_FAILURE`
export const SET_DELETE_MODAL_OPEN = `${POST_ACTIONS_PREFIX}SET_DELETE_POST_MODAL_OPEN`
