const AUTH_ACTIONS_PREFIX = 'auth/'

export const CHECK_AUTH_REQUEST = `${AUTH_ACTIONS_PREFIX}CHECK_AUTH_REQUEST`
export const CHECK_AUTH_SUCCESS = `${AUTH_ACTIONS_PREFIX}CHECK_AUTH_SUCCESS`
export const CHECK_AUTH_FAILURE = `${AUTH_ACTIONS_PREFIX}CHECK_AUTH_FAILURE`

export const LOGIN_REQUEST = `${AUTH_ACTIONS_PREFIX}LOGIN_REQUEST`
export const LOGIN_SUCCESS = `${AUTH_ACTIONS_PREFIX}LOGIN_SUCCESS`
export const LOGIN_FAILURE = `${AUTH_ACTIONS_PREFIX}LOGIN_FAILURE`

export const LOGOUT = `${AUTH_ACTIONS_PREFIX}LOGOUT`
